image: codefreshplugins/cfstep-paclair
categories:
  - security
tag: 3.1.0
version: 0.1.0
description: "Scan docker images with Clair - https://github.com/coreos/clair"
keywords:
  - docker
  - clair
  - security
sources:
  - https://github.com/codefresh-contrib/cfstep-paclair
maintainers:
  - name: Dustin Van Buskirk
    email: dustinb@codefresh.io
icon: https://raw.githubusercontent.com/codefresh-plugins/cfstep-paclair/master/icon.jpg
envs:
  - name: API_PREFIX
    description: "Prefix for API to Docker Registry"
  - name: CLAIR_URL 
    description: https://clair.domain.com:6060
  - name: IMAGE 
    description: "Docker Image Name"
  - name: PROTOCOL 
    description: "Docker Registry Protocol"
  - name: REGISTRY 
    description: "For ECR use `ecr` else use domain name for Docker Registry"
  - name: REGISTRY_PASSWORD 
    description: Docker Registry Password 
  - name: REGISTRY_USERNAME 
    description: Docker Registry Username 
  - name: SEVERITY_THRESHOLD
    description: "critical, high, medium, low, negligible, unknown"
  - name: TOKEN 
    description: "Docker Registry Auth Token"
  - name: TOKEN_TYPE
    description: "Docker Registry Auth Token Type"
  - name: TOKEN_URL
    description: "Docker Registry Auth Token URL"
  - name: TAG 
    description: "Docker Image Tag"
