apiVersion: v1
kind: Service
metadata:
  name: my-demo-app
  namespace: colors
spec:
  ports:
  - name: http1
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: my-demo-app
    version: 'c39f076'
  sessionAffinity: None
  type: LoadBalancer
