image: codefreshplugins/gitternotifier
version: 0.1.0
description: Send message to gitter 
categories:
  - messaging
keywords:
  - gitter
sources:
  - https://github.com/codefresh-contrib/gitter-notifier
maintainers: # (optional)
  - name: Andrii Shaforostov
    email: andrii@codefresh.io
icon: https://raw.githubusercontent.com/codefresh-plugins/gitter-notifier/master/logo2.png
envs:
  - name: GITTER_WEBHOOK
    type: required
    description: gitter webhook
  - name: GITTER_STATUS
    description: send info about current build
  - name: GITTER_MESSAGE
    description: text of message which will be sent in room
