apiVersion: v2
appVersion: 1.0.0
dependencies:
- import-values:
  - three
  - four
  name: my-subchart
  repository: http://codefreshiest.mostest.com/charts
  tags:
  - t3
  version: 1.2.3
description: blah
keywords:
- weird
- strange
- good
- bad
kubeVersion: '1.16'
name: my-chart
sources:
- http://example.com
type: application
version: 1.0.50
