version: '1.0'

steps:
  define_the_versions_list:
    image: alpine
    commands:
      - |- 
        cat <<EOF > helmVersionsList 
        2.9.0
        2.9.1
        2.10.0
        2.11.0
        2.12.0
        2.12.1
        2.12.2
        2.12.3
        2.13.0
        2.13.1
        2.14.0
        2.14.1
        2.14.2
        2.14.3
        2.15.0
        2.15.1
        2.15.2
        2.16.0
        2.16.1
        3.0.0-beta.2
        3.0.0-beta.3
        3.0.0
        3.0.1
        3.0.2
    when:
      condition:
        all:
          notRecursivelyInvoked: 'includes("${{HELM_VERSION}}", "${{") == true'

  run-cli-loop:
    image: codefresh/cli
    commands:
      - for VAR in $(cat helmVersionsList); do codefresh wait $(codefresh run ${{CF_PIPELINE_NAME}} -d --branch ${{CF_BRANCH}} --variable HELM_VERSION=${VAR} --trigger ${{CF_PIPELINE_TRIGGER_ID}} --context github) & done
      - for j in $(jobs -p); do wait $j || (echo "Failed to build one of the images" && ! break); done
    when:
      condition:
        all:
          notRecursivelyInvoked: 'includes("${{HELM_VERSION}}", "${{") == true'

  clone:
    type: git-clone
    arguments:
      repo: '${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}'
      git: github
      revision: '${{CF_REVISION}}'
      when:
        condition:
          all:
            recursivelyInvoked: 'includes("${{HELM_VERSION}}", "${{") == false'

  build_image:
    type: build
    working_directory: '${{clone}}'
    image_name: '${{STEP_IMAGE}}'
    tag: '${{HELM_VERSION}}-${{CF_SHORT_REVISION}}'
    build_arguments:
      - 'HELM_VERSION=${{HELM_VERSION}}'
      - 'S3_PLUGIN_VERSION=0.8.0'
      - 'GCS_PLUGIN_VERSION=0.2.0'
      - 'PUSH_PLUGIN_VERSION=0.7.1'
    when:
      condition:
        all:
          recursivelyInvoked: 'includes("${{HELM_VERSION}}", "${{") == false'

  push:
    type: push
    registry: dockerhub
    tag: ${{HELM_VERSION}}
    candidate: ${{build_image}}
    when:
      condition:
        all:
          recursivelyInvoked: 'includes("${{HELM_VERSION}}", "${{") == false'
          masterBranch: 'match("${{CF_BRANCH}}", "^master", true) == true'

  push_latest:
    type: push
    registry: dockerhub
    tag: latest
    candidate: ${{build_image}}
    when:
      condition:
        all:
          latestHelmVersion: "'${{HELM_VERSION}}' == '${{LATEST_VERSION}}'"
          masterBranch: "'${{CF_BRANCH}}' == 'master'"