name: BitBucket Pull-Request Plugin
image: codefreshplugins/bitbucket-pr
tag: "0.1"
version: "0.1"
description: Open and Annotate BitBucket PullRequests
categories:
- git
sources:
- https://github.com/codefresh-contrib/bitbucket-pr
maintainers:
- name: Ant Weiss
  email: ant.weiss@codefresh.io
icon: https://raw.githubusercontent.com/codefresh-plugins/bitbucket-pr/master/icon.jpg
envs:
- name: MY_VAR
  type: required
  description: placeholder
